// No longer directly calls OpenAI or mocks complex AI responses.
// Its role is simplified to prepare data if needed and pass it to dataService for backend sync.
// Actual AI processing and insight generation would occur on the backend based on synced rawData.
import dataService from './dataService'; // dataService now handles backend communication

// analyzeMoodFromData now primarily ensures data is prepared and then stored via dataService.
// The 'AI analysis' is implicitly what the backend might do with this data later.
// The data returned to the dashboard will be the synced data from the backend via dataService.getMoodHistory.
const analyzeMoodFromData = async (dailyData) => {
  if (!dailyData) {
    console.error('aiService.analyzeMoodFromData: dailyData is required.');
    return { success: false, message: 'Daily data is required for analysis sync.' };
  }

  // Here, dailyData is expected to be the comprehensive object ready for the backend,
  // typically generated by something like dataService.getMockDailyData() or real sensor aggregation.
  // It should include fields like: date, primaryMood, confidence, activities, summary, rawData, etc.

  // The responsibility of this function is now to trigger the storage (and thereby backend sync)
  // of this data. The "analysis" part is that this data will BECOME the analysis record.
  console.log('aiService: Passing data to dataService.storeMoodAnalysis:', dailyData);

  try {
    // dataService.storeMoodAnalysis will send it to the backend.
    const response = await dataService.storeMoodAnalysis(dailyData);

    if (response.success) {
      console.log('aiService: Data successfully processed by dataService (synced to backend).');
      // Return the response which includes the backend-confirmed data
      return { success: true, data: response.data };
    } else {
      console.error('aiService: Failed to process data via dataService:', response.message);
      return { success: false, message: response.message || 'Failed to store/sync daily data.' };
    }
  } catch (error) {
    console.error('aiService: Error calling dataService.storeMoodAnalysis:', error);
    return { success: false, message: error.message || 'Client-side error in aiService.' };
  }
};

export default {
  analyzeMoodFromData,
};
